Repository gdgtoledo/web, pull requests merged in 2019-07, with the labels that each got.

#25 [#12] Document build process
  README.md
Labels: docs, medium

#30 [#24] fix horizontal scroll
  assets/css/style.css
Labels: bug

#28 26
  Dockerfile
  Gemfile_.lock
  README.md
  _config.yml
  _meetups/2017-10-26-jekyll-no-comliques-lo-que-es-sencillo.md
  _meetups/2017-12-02-vueling-aprendiendo-vue-js.md
  docker-compose.yml
Labels: chore, docs, low
