Repository gdgtoledo/web, pull requests merged in 2020-03, with the labels that each got.

#102 chore: Añadir un comando de run al build
  Dockerfile
  Makefile
  README.md
  _config.yml
  docker-compose.yml
Labels: chore

#111 Mejorar la UX de los posts
  _includes/meetups.html
  _includes/posts.html
  _layouts/post.html
  assets/css/style.css
  docs/assets/css/style.css
  docs/credits/index.html
  docs/meetups/2/index.html
  docs/meetups/index.html
  docs/posts/2013-11-10-hola-mundo/index.html
  docs/posts/2020-04-16-cansino/index.html
  docs/posts/index.html
Labels: bug, enhancement

#128 Añadir margenes para hacer mas legibles los post
  _layouts/meetups.html
  _layouts/posts.html
  assets/css/style.css
  docs/assets/css/style.css
  docs/meetups/2/index.html
  docs/meetups/3/index.html
  docs/meetups/index.html
  docs/posts/index.html
Labels: enhancement
